# Generated by Django 4.0.6 on 2022-07-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shoppingitem_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingitem',
            options={'ordering': ['added']},
        ),
    ]
